# Generated by Django 4.0.4 on 2022-06-20 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Album_name', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('genres', models.CharField(blank=True, choices=[('po', 'pop'), ('cl', 'classic'), ('ro', 'rock'), ('hi', 'hip hop')], max_length=2)),
                ('cover', sorl.thumbnail.fields.ImageField(upload_to='album_covers/')),
            ],
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('language', models.CharField(blank=True, choices=[('iri', 'farsi'), ('eng', 'english')], max_length=3)),
                ('audio', models.FileField(blank=True, upload_to='audios/')),
                ('cover', sorl.thumbnail.fields.ImageField(blank=True, upload_to='covers/')),
                ('download_link', models.CharField(max_length=100)),
                ('rating', models.IntegerField(choices=[(1, 'poor'), (2, 'average'), (3, 'good'), (4, 'very good'), (5, 'excellent')], default=1)),
                ('genres', models.CharField(choices=[('po', 'pop'), ('cl', 'classic'), ('ro', 'rock'), ('hi', 'hip hop')], default=1, max_length=2)),
                ('instrument_used', models.CharField(blank=True, choices=[('pi', 'piano'), ('vi', 'violin'), ('gu', 'guitar'), ('fl', 'flute')], max_length=2)),
                ('view_number', models.PositiveIntegerField(default=0)),
                ('Album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musics.album')),
                ('Artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musics.artists')),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.music')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100)),
                ('audios', models.FileField(upload_to='playlist_audios/')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_favorit', models.BooleanField(default=False)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='Artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musics.artists'),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
